package constants

const SPACE = "http://www.filemaker.com/fmpxmlresult"

const FMPXMLRESULT = "FMPXMLRESULT"
const ERRORCODE = "ERRORCODE"
const PRODUCT = "PRODUCT"
const BUILD = "BUILD"
const VERSION = "VERSION"
const DATABASE = "DATABASE"
const DATEFORMAT = "DATEFORMAT"
const LAYOUT = "LAYOUT"
const NAME = "NAME"
const RECORDS = "RECORDS"
const TIMEFORMAT = "TIMEFORMAT"
const METADATA = "METADATA"
const FIELD = "FIELD"
const RESULTSET = "RESULTSET"
const ROW = "ROW"
const MODID = "MODID"
const RECORDID = "RECORDID"
const COL = "COL"
const DATA = "DATA"
const EMPTYOK = "EMPTYOK"
const MAXREPEAT = "MAXREPEAT"
const TYPE = "TYPE"

const NUMBER = "NUMBER"
const DATE = "DATE"
const TIME = "TIME"
const TIMESTAMP = "TIMESTAMP"
